[versions]
adventure = "4.18.0"
adventurePlatformBukkit = "4.3.4"
cloudAnnotations = "2.0.0"
cloudPaper = "2.0.0-beta.10"
cloudMinecraftExtras = "2.0.0-beta.10"
commodore = "2.2"
jsoup = "1.18.3"
fastboard = "2.1.3"
inventoryFramework = "0.10.19"
bstatsBukkit = "3.1.0"
hibernateCore = "7.0.0.Beta1"
h2 = "2.3.232"
byteBuddy = "1.15.11"
byteBuddyAgent = "1.15.11"
spigotApi = "1.21.4-R0.1-SNAPSHOT"
fastutil = "5.0.9"
nettyAll = "4.1.97.Final"
placeholderapi = "2.11.6"
protocolLib = "5.3.0"
libsDisguises = "10.0.44"
worldeditCore = "7.3.9"
worldeditBukkit = "7.3.9"
citizensMain = "2.0.35-SNAPSHOT"
classGraph = "4.8.179"
guava = "32.1.3-jre"
gson = "2.11.0"

[libraries]
adventureApi = { group = "net.kyori", name = "adventure-api", version.ref = "adventure" }
adventurePlatformBukkit = { group = "net.kyori", name = "adventure-platform-bukkit", version.ref = "adventurePlatformBukkit" }
adventureTextMinimessage = { group = "net.kyori", name = "adventure-text-minimessage", version.ref = "adventure" }
adventureTextSerializerPlain = { group = "net.kyori", name = "adventure-text-serializer-plain", version.ref = "adventure" }
adventureTextSerializerLegacy = { group = "net.kyori", name = "adventure-text-serializer-legacy", version.ref = "adventure" }
cloudAnnotations = { group = "org.incendo", name = "cloud-annotations", version.ref = "cloudAnnotations" }
cloudPaper = { group = "org.incendo", name = "cloud-paper", version.ref = "cloudPaper" }
cloudMinecraftExtras = { group = "org.incendo", name = "cloud-minecraft-extras", version.ref = "cloudMinecraftExtras" }
commodore = { group = "me.lucko", name = "commodore", version.ref = "commodore" }
jsoup = { group = "org.jsoup", name = "jsoup", version.ref = "jsoup" }
fastboard = { group = "fr.mrmicky", name = "fastboard", version.ref = "fastboard" }
inventoryFramework = { group = "com.github.stefvanschie.inventoryframework", name = "IF", version.ref = "inventoryFramework" }
bstatsBukkit = { group = "org.bstats", name = "bstats-bukkit", version.ref = "bstatsBukkit" }
hibernateCore = { group = "org.hibernate.orm", name = "hibernate-core", version.ref = "hibernateCore" }
h2 = { group = "com.h2database", name = "h2", version.ref = "h2" }
byteBuddy = { group = "net.bytebuddy", name = "byte-buddy", version.ref = "byteBuddy" }
byteBuddyAgent = { group = "net.bytebuddy", name = "byte-buddy-agent", version.ref = "byteBuddyAgent" }
spigotApi = { group = "org.spigotmc", name = "spigot-api", version.ref = "spigotApi" }
fastutil = { group = "fastutil", name = "fastutil", version.ref = "fastutil" }
nettyAll = { group = "io.netty", name = "netty-all", version.ref = "nettyAll" }
placeholderapi = { group = "me.clip", name = "placeholderapi", version.ref = "placeholderapi" }
protocolLib = { group = "com.comphenix.protocol", name = "ProtocolLib", version.ref = "protocolLib" }
libsDisguises = { group = "LibsDisguises", name = "LibsDisguises", version.ref = "libsDisguises" }
worldeditCore = { group = "com.sk89q.worldedit", name = "worldedit-core", version.ref = "worldeditCore" }
worldeditBukkit = { group = "com.sk89q.worldedit", name = "worldedit-bukkit", version.ref = "worldeditBukkit" }
citizensMain = { group = "net.citizensnpcs", name = "citizens-main", version.ref = "citizensMain" }
classGraph = { group = "io.github.classgraph", name = "classgraph", version.ref = "classGraph" }
guava = { group = "com.google.guava", name = "guava", version.ref = "guava" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }